<?php

@include('teacherapi.php');

Route::post('/parent/login', 'Api\TokenController@issueToken');
Route::post('/logout/devices', 'Api\LoginController@logoutDevices');
Route::get('/schools/list','Api\SchoolController@list');
Route::get('/apk/parent','Api\ApkController@parentApp');
Route::get('/apk/teacher','Api\ApkController@teacherApp');
Route::post('/password/reset', 'Api\UserController@resetPassword');
Route::post('/password/store', 'Api\UserController@storePassword');
Route::post('/reset/check', 'Api\UserController@checkReset');
Route::post('/reset/change/password', 'Api\UserController@resetChangePassword');
Route::get('/school/info', 'Api\SchoolController@schooldetail');

Route::group(['prefix' => 'v2', 'namespace' =>'Api', 'middleware' => ['auth:sanctum']], function () {
    Route::post('/logout', 'LoginController@logout');
    Route::get('/myinfo', 'MeController@myInfo');
    Route::get('/updatetoken', 'UserController@updatetoken');
    Route::post('/password/change', 'UserController@changePassword');
    Route::get('/my-children', 'ChildrenController@listChildren');
    Route::get('/my-children/count', 'ChildrenController@countChildren');
    Route::get('/my-children/{id}/details', 'ChildrenController@showChildren');
    Route::get('/school/details', 'SchoolController@index');
    Route::get('/holiday/list','EventsController@holidaylist');
    Route::get('/my-school/magazine', 'BulletinsController@show');
    Route::get('/my-school/list-events', 'EventsController@index');
    Route::get('/my-events/upcoming', 'EventsController@upcoming');
    Route::get('/my-events/past', 'EventsController@showpast');
    Route::get('/my-events/school', 'EventsController@school');
    Route::get('/my-events/{student_id}/class', 'EventsController@class');
    Route::get('/my-events/show/{id}', 'EventsController@show');
    Route::get('/my-events/gallery/show/{event_id}', 'EventGalleryController@showimage');
    Route::get('/leaves/{student_id}','LeaveController@index');
    Route::get('/leave/list','LeaveController@create');
    Route::post('/leave/add/{student_id}','LeaveController@store');
    Route::get('/leave/show/{id}','LeaveController@show');
    Route::post('/leave/edit/{id}','LeaveController@update');
    Route::get('/leave/delete/{id}','LeaveController@destroy');
    Route::get('/messages','FeedbackController@sentMessages');
    Route::get('/notifications/{studentid}','FeedbackController@notifications');
    Route::post('/message/read/{id}','FeedbackController@readMessage');
    Route::get('/feedbacks','FeedbackController@index');
    Route::get('/feedback/category/list','FeedbackController@list');
    Route::post('/feedback/send/{student_id}','FeedbackController@store');
    Route::get('/disciplines/{student_id}','DisciplineController@index');
    Route::get('/discipline/show/{id}','DisciplineController@show');
    Route::get('/performance/{student_id}','DisciplineController@performance');
    Route::get('/homeworks/pending/{student_id}','HomeworkController@pending');
    Route::get('/homeworks/finished/{student_id}','HomeworkController@finished');
    Route::get('/homework/show/{student_id}/{id}','HomeworkController@show');
    Route::post('/homework/submit/{homework_id}/{student_id}','HomeworkController@store');
    Route::delete('/homework/delete/{id}/{student_id}','HomeworkController@destroy');
    Route::post('/homework/reply/{homework_id}/{student_id}','HomeworkController@replycomment');
    Route::get('/lessonplan/{student_id}','LessonPlanController@index');
    Route::get('/lessonplan/print/{id}','LessonPlanController@print');
    Route::get('/lessonplan/{student_id}/{subject_id}','LessonPlanController@subjectIndex');
    Route::get('/my-school/notices','NoticeBoardController@indexSchool');
    Route::get('/my-school/notices/expired','NoticeBoardController@expiredSchool');
    Route::get('/notices/{student_id}','NoticeBoardController@indexClass');
    Route::get('/notices/expired/{student_id}','NoticeBoardController@expiredClass');
    Route::get('/notice/show/{id}','NoticeBoardController@show');
    Route::get('/attendance/{student_id}','AttendanceController@index');
    Route::get('/teachers/{student_id}','TeacherController@index');
    Route::get('/assignments/{student_id}','AssignmentController@index');
    Route::get('/assignments/completed/{student_id}','AssignmentController@completed');
    Route::get('/assignment/show/{student_id}/{id}','AssignmentController@show');
    Route::post('/assignment/submit/{assignment_id}/{student_id}','AssignmentController@store');
    Route::delete('/assignment/delete/{id}/{student_id}','AssignmentController@destroy');
    Route::get('/mytasks/active/{student_id}','TaskController@myActiveList');
    Route::get('/mytasks/completed/{student_id}','TaskController@myCompletedList');
    Route::get('/tasks/active/{student_id}','TaskController@activeList');
    Route::get('/tasks/completed/{student_id}','TaskController@completedList');
    Route::post('/tasks/mark/complete','TaskController@changestatus');
    Route::get('/task/add/list','TaskController@create');
    Route::post('/task/add/{student_id}','TaskController@store');
    Route::get('/task/show/{id}','TaskController@show');
    Route::get('/task/edit/{id}','TaskController@edit');
    Route::post('/task/edit/{id}/{student_id}','TaskController@update');
    Route::post('/task/snooze/{id}/{student_id}', 'TaskController@snooze');
    Route::get('/task/delete/{id}','TaskController@destroy');
    Route::post('/student/modules','StudentHistoryController@update');
    Route::get('/addons','PurchaseHistoryController@index');
});

Route::get('/bloodGroup/list','Api\TestController@getBloodGroup');
Route::get('/get/country','Api\UserprofileController@country');
Route::get('/get/state/{id}','Api\UserprofileController@state');
Route::get('/get/city/{id}','Api\UserprofileController@city');
Route::get('/events/show/details/{id}','Api\EventsController@showdetails');

require base_path('routes/tagore.php');
