[Reading 15 lines from start (total: 15 lines, 0 remaining)]

@extends('layouts.app')
@section('base-content')
<link rel="stylesheet" href="{{ asset('tagore-erp.css') }}">
<div class="tg-app"><div class="tg-shell">
<header class="tg-topbar"><div class="tg-brand"><div class="tg-logo">T</div><div><strong>TagoreK12</strong><span>Transport Control</span></div></div><a class="tg-btn" href="{{ route('tagore.dashboard') }}">ERP Home</a></header>
@if(session('success'))<div class="tg-alert success">{{ session('success') }}</div>@endif
@if($errors->any())<div class="tg-alert danger">{{ $errors->first() }}</div>@endif
<section class="tg-hero"><div><span class="tg-eyebrow">Transport</span><h1>Routes, Vehicles & Live Trips</h1><p>GPS pings, live trip data and boarding/deboarding events are available to the transport app and parent dashboard.</p></div></section>
<section class="tg-card"><h2>Create route</h2><form class="tg-form" method="POST" action="{{ route('tagore.transport.route') }}">@csrf<div class="tg-grid"><label class="tg-field"><span>Institution</span><select name="institution_id" required>@foreach($institutions as $i)<option value="{{ $i->id }}">{{ $i->display_name }}</option>@endforeach</select></label><label class="tg-field"><span>Name</span><input name="name" required></label><label class="tg-field"><span>Stops JSON</span><textarea name="stops_json" placeholder='[{"name":"Stop 1","lat":28.0,"lng":75.0}]'></textarea></label><label class="tg-field"><span>Estimated minutes</span><input type="number" name="estimated_minutes" min="0" value="0"></label><label class="tg-field"><span>Transport fee</span><input type="number" name="fee" step="0.01" min="0" value="0"></label></div><button class="tg-btn primary">Create route</button></form></section>
<section class="tg-card"><h2>Add vehicle</h2><form class="tg-form" method="POST" action="{{ route('tagore.transport.vehicle') }}">@csrf<div class="tg-grid"><label class="tg-field"><span>Institution</span><select name="institution_id" required>@foreach($institutions as $i)<option value="{{ $i->id }}">{{ $i->display_name }}</option>@endforeach</select></label><label class="tg-field"><span>Registration</span><input name="registration_no" required></label><label class="tg-field"><span>Type</span><input name="vehicle_type" value="bus"></label><label class="tg-field"><span>Capacity</span><input type="number" name="capacity" min="1" required></label><label class="tg-field"><span>GPS device ID</span><input name="gps_device_id"></label></div><button class="tg-btn primary">Add vehicle</button></form></section>
<section class="tg-card"><h2>Register driver</h2><form class="tg-form" method="POST" action="{{ route('tagore.transport.driver') }}">@csrf<div class="tg-grid"><label class="tg-field"><span>Institution</span><select name="institution_id" required>@foreach($institutions as $i)<option value="{{ $i->id }}">{{ $i->display_name }}</option>@endforeach</select></label><label class="tg-field"><span>User ID</span><input type="number" name="user_id" required></label><label class="tg-field"><span>License no.</span><input name="license_no"></label><label class="tg-field"><span>License expiry</span><input type="date" name="license_expiry"></label></div><button class="tg-btn primary">Register driver</button></form></section>
<section class="tg-card"><h2>Start trip</h2><form class="tg-form" method="POST" action="{{ route('tagore.transport.trip') }}">@csrf<div class="tg-grid"><label class="tg-field"><span>Institution</span><select name="institution_id" required>@foreach($institutions as $i)<option value="{{ $i->id }}">{{ $i->display_name }}</option>@endforeach</select></label><label class="tg-field"><span>Route</span><select name="route_id">@foreach($routes as $r)<option value="{{ $r->id }}">{{ $r->name }}</option>@endforeach</select></label><label class="tg-field"><span>Vehicle</span><select name="vehicle_id">@foreach($vehicles as $v)<option value="{{ $v->id }}">{{ $v->registration_no }}</option>@endforeach</select></label><label class="tg-field"><span>Driver</span><select name="driver_id"><option value="">—</option>@foreach($drivers as $d)<option value="{{ $d->id }}">{{ $d->driver_name }}</option>@endforeach</select></label></div><button class="tg-btn primary">Start trip</button></form></section>
<section class="tg-card"><h2>Trips</h2><div class="tg-table-wrap"><table><thead><tr><th>Route</th><th>Vehicle</th><th>Status</th><th>Started</th><th>Live API</th></tr></thead><tbody>@foreach($trips as $t)<tr><td>{{ $t->route_name }}</td><td>{{ $t->registration_no }}</td><td>{{ $t->status }}</td><td>{{ $t->started_at }}</td><td><a class="tg-btn" href="{{ route('tagore.transport.live',$t->id) }}">JSON</a></td></tr>@endforeach</tbody></table></div></section>
</div></div>
@endsection

[executed on device: DESKTOP-564ES39 (d76c0fdf-a9a5-457e-b21a-81313e01406e)]