@extends('layouts.app')
@section('content')
<link rel="stylesheet" href="{{ asset('tagore-erp.css') }}">
<div class="tg-app"><div class="tg-shell">
<header class="tg-topbar"><div class="tg-brand"><div class="tg-logo">T</div><div><strong>TagoreK12</strong><span>Report Builder</span></div></div><a class="tg-btn" href="{{ route('tagore.dashboard') }}">ERP Home</a></header>
@if(session('success'))<div class="tg-alert success">{{ session('success') }}</div>@endif
@if($errors->any())<div class="tg-alert danger">{{ $errors->first() }}</div>@endif
<section class="tg-hero"><div><span class="tg-eyebrow">Analytics</span><h1>Custom Report Builder</h1><p>Select a safe data source and fields, save the definition, then export CSV or PDF.</p></div></section>
<section class="tg-card"><h2>Save report definition</h2><form class="tg-form" method="POST" action="{{ route('tagore.reports.save') }}">@csrf<div class="tg-grid"><label class="tg-field"><span>Institution</span><select name="institution_id" required>@foreach($institutions as $i)<option value="{{ $i->id }}">{{ $i->display_name }}</option>@endforeach</select></label><label class="tg-field"><span>Name</span><input name="name" required></label><label class="tg-field"><span>Source</span><select name="source" id="report-source" onchange="loadColumns()"><option value="payroll_runs">Payroll runs</option><option value="payroll_items">Payroll items</option><option value="inventory">Inventory</option><option value="expenses">Expenses</option><option value="assets">Assets</option><option value="transport_trips">Transport trips</option><option value="communications">Communications</option></select></label><label class="tg-field"><span>Format</span><select name="format"><option>table</option><option>csv</option><option>pdf</option></select></label><label class="tg-field" style="grid-column:1/-1"><span>Columns (comma separated)</span><input name="columns_text" id="columns-text" value="id,institution_id,month,status,gross_total,deduction_total,net_total" oninput="syncColumns()"><input type="hidden" name="columns[]" id="columns-hidden"></label></div><button class="tg-btn primary">Save report</button></form></section>
<section class="tg-card"><h2>Saved reports</h2><div class="tg-table-wrap"><table><thead><tr><th>Name</th><th>Source</th><th>Format</th><th>Actions</th></tr></thead><tbody>@foreach($reports as $r)<tr><td>{{ $r->name }}</td><td>{{ $r->module }}</td><td>{{ $r->format }}</td><td><a class="tg-btn" href="{{ route('tagore.reports.export',$r->id,['format'=>'csv']) }}">CSV</a><a class="tg-btn" href="{{ route('tagore.reports.export',$r->id,['format'=>'pdf']) }}">PDF</a></td></tr>@endforeach</tbody></table></div></section>
</div></div>
<script>
const cols={payroll_runs:'id,institution_id,month,status,gross_total,deduction_total,net_total',payroll_items:'id,payroll_run_id,employee_id,basic_salary,gross_amount,pf_amount,esi_amount,tds_amount,other_deductions,net_amount,status',inventory:'id,institution_id,name,sku,category,unit,quantity,reorder_level,unit_cost,status',expenses:'id,institution_id,expense_date,department,category,description,amount,vendor,status',assets:'id,institution_id,asset_tag,name,category,purchase_date,cost,department,assigned_to,status',transport_trips:'id,institution_id,route_id,vehicle_id,driver_id,started_at,ended_at,status',communications:'id,institution_id,title,channel,scheduled_at,status,sent_count,failed_count'};
function loadColumns(){document.getElementById('columns-text').value=cols[document.getElementById('report-source').value];syncColumns();}
function syncColumns(){const h=document.getElementById('columns-hidden');h.value='';document.querySelectorAll('#columns-hidden').forEach(x=>x.remove());const form=document.querySelector('form');document.getElementById('columns-text').value.split(',').map(x=>x.trim()).filter(Boolean).forEach(x=>{const i=document.createElement('input');i.type='hidden';i.name='columns[]';i.value=x;form.appendChild(i);});}
syncColumns();
</script>
@endsection
