<!doctype html>
<html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>{{ $department->name }} | TagoreK12</title>
<style>body{font-family:system-ui,-apple-system,sans-serif;background:#f4f7fb;color:#172033;margin:0}.shell{max-width:1250px;margin:auto;padding:24px 16px 60px}.card{background:#fff;border:1px solid #e2e8f0;border-radius:12px;padding:16px;margin-top:14px}.grid{display:grid;grid-template-columns:repeat(6,1fr);gap:10px}.metric b{display:block;font-size:25px}.muted{color:#64748b;font-size:13px}table{width:100%;border-collapse:collapse}th,td{padding:9px;border-bottom:1px solid #edf2f7;text-align:left;font-size:13px}a{color:#2563eb;text-decoration:none}.toolbar{display:flex;justify-content:space-between;gap:12px;align-items:end;flex-wrap:wrap}.toolbar select{padding:9px;border:1px solid #cbd5e1;border-radius:8px;background:#fff}.two{display:grid;grid-template-columns:2fr 1fr;gap:14px}@media(max-width:900px){.grid{grid-template-columns:repeat(3,1fr)}.two{grid-template-columns:1fr}}@media(max-width:550px){.grid{grid-template-columns:repeat(2,1fr)}}</style></head>
<body><div class="shell">
<p><a href="{{ route('tagore.dashboard') }}">← Manager Command Center</a></p>
<div class="card toolbar"><div><h1 style="margin:0">{{ $department->name }}</h1><div class="muted">{{ $department->code }} · {{ $department->institution }}</div></div>
<form><label class="muted">Analytics period</label><br><select name="period" onchange="this.form.submit()"><option value="7" @selected($analyticsDays===7)>7 days</option><option value="30" @selected($analyticsDays===30)>30 days</option><option value="90" @selected($analyticsDays===90)>90 days</option></select></form></div>
<div class="grid">@foreach([['Total tasks',$stats['assigned']],['Active',$stats['active']],['Completed',$stats['completed']],['Overdue',$stats['overdue']],['Blocked',$stats['blocked']],['All-time completion',$stats['completion_rate'].'%']] as $m)<div class="card metric"><span class="muted">{{ $m[0] }}</span><b>{{ $m[1] }}</b></div>@endforeach</div>
<div class="grid">@foreach([['Created in period',$periodStats['created']],['Completed in period',$periodStats['completed']],['Net workload',$periodStats['net']],['Period completion',$periodStats['completion_rate'].'%']] as $m)<div class="card metric"><span class="muted">{{ $m[0] }}</span><b>{{ $m[1] }}</b></div>@endforeach</div>
<div class="two"><div class="card"><h2>{{ $analyticsDays }}-day workload trend</h2><table><tr><th>Date</th><th>Created</th><th>Completed</th><th>Net</th></tr>@foreach($trend as $day)<tr><td>{{ date('d M',strtotime($day->day)) }}</td><td>{{ $day->created }}</td><td>{{ $day->completed }}</td><td>{{ $day->created-$day->completed }}</td></tr>@endforeach</table></div>
<div class="card"><h2>Health</h2><p><span class="muted">Active workload</span><br><b>{{ $stats['active'] }}</b></p><p><span class="muted">Overdue</span><br><b>{{ $stats['overdue'] }}</b></p><p><span class="muted">Blocked</span><br><b>{{ $stats['blocked'] }}</b></p><p><span class="muted">Period net</span><br><b>{{ $periodStats['net'] }}</b></p></div></div>
<div class="card"><h2>Employee workload &amp; performance</h2><table><tr><th>Employee</th><th>Designation</th><th>Created</th><th>Completed</th><th>Active</th><th>Overdue</th><th>Blocked</th><th>Completion</th></tr>@forelse($employees as $employee)<tr><td><a href="{{ route('tagore.tasks.employee',$employee->id) }}">{{ $employee->name }}</a></td><td>{{ $employee->designation ?: '—' }}</td><td>{{ $employee->period_created }}</td><td>{{ $employee->period_completed }}</td><td>{{ $employee->active }}</td><td>{{ $employee->overdue }}</td><td>{{ $employee->blocked }}</td><td>{{ $employee->period_completion_rate }}%</td></tr>@empty<tr><td colspan="8">No department staff mapped.</td></tr>@endforelse</table></div>
<div class="card"><h2>Pending follow-ups</h2>@if($followups->isEmpty())<div class="muted">No pending action-required follow-ups.</div>@else<table><tr><th>Employee</th><th>Task</th><th>Outcome</th><th>Follow-up</th></tr>@foreach($followups as $f)<tr><td>{{ $f->employee_name }}</td><td>{{ $f->task_title ?: '—' }}</td><td>{{ ucfirst(str_replace('_',' ',$f->outcome)) }}</td><td>{{ $f->follow_up_at ? date('d M Y H:i',strtotime($f->follow_up_at)) : 'Unscheduled' }}</td></tr>@endforeach</table>@endif</div>
</div></body></html>