<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{{ $student->name }} · Tagore ERP</title><link rel="stylesheet" href="{{ asset('tagore-erp.css') }}"></head>
<body class="tg-app"><div class="tg-shell">
<header class="tg-topbar"><a class="tg-brand" href="{{ route('tagore.dashboard') }}" style="text-decoration:none"><div class="tg-logo">T</div><div><strong>Tagore ERP</strong><span>Student profile</span></div></a><div class="tg-actions"><a class="tg-btn" href="{{ route('tagore.dashboard') }}">← Dashboard</a></div></header>
<main class="tg-main">
<section class="tg-hero"><h1>{{ $student->name }}</h1><p>{{ $student->institution ?: 'Tagore Institution' }} · A simple, complete view of the student's school journey.</p><div class="tg-hero-actions"><a class="tg-btn primary" href="{{ route('tagore.fees.student',$student->id) }}">View fees</a><a class="tg-btn" href="{{ route('tagore.dashboard') }}">Back to home</a></div></section>
<div class="tg-grid">
<div class="tg-card tg-kpi"><div class="tg-kpi-label">Fee outstanding</div><div class="tg-kpi-value">₹{{ number_format($fees->sum('outstanding_amount'),0) }}</div><div class="tg-kpi-meta">{{ $fees->whereIn('status',['pending','partial','overdue'])->count() }} open items</div></div>
<div class="tg-card tg-kpi"><div class="tg-kpi-label">Fee paid</div><div class="tg-kpi-value">₹{{ number_format($fees->sum('paid_amount'),0) }}</div><div class="tg-kpi-meta">Recorded payments</div></div>
<div class="tg-card tg-kpi"><div class="tg-kpi-label">Attendance</div><div class="tg-kpi-value">{{ $attendancePercent === null ? '—' : $attendancePercent.'%' }}</div><div class="tg-kpi-meta">{{ $attendance && $attendance->total ? ($attendance->present ?: 0).' of '.$attendance->total.' present' : 'No records yet' }}</div></div>
<div class="tg-card tg-kpi"><div class="tg-kpi-label">Published results</div><div class="tg-kpi-value">{{ $results->count() }}</div><div class="tg-kpi-meta">Available for review</div></div>
</div>
<section class="tg-section tg-two">
<div class="tg-card" style="padding:18px"><div class="tg-section-head"><div><h2>Fee activity</h2><p>Current obligations and payment status</p></div></div>
@if($fees->isEmpty())<div class="tg-empty"><strong>No fee obligations</strong><span>No fee records have been published for this student.</span></div>
@else<div style="overflow:auto"><table class="table"><tr><th>Due</th><th>Amount</th><th>Paid</th><th>Balance</th><th>Status</th></tr>@foreach($fees->take(10) as $fee)<tr><td>{{ $fee->due_date ?: '—' }}</td><td>₹{{ number_format($fee->net_amount,0) }}</td><td>₹{{ number_format($fee->paid_amount,0) }}</td><td>₹{{ number_format($fee->outstanding_amount,0) }}</td><td><span class="tg-status {{ in_array($fee->status,['overdue','pending']) ? 'warning' : 'success' }}">{{ ucfirst($fee->status) }}</span></td></tr>@endforeach</table></div>@endif</div>
<div class="tg-card" style="padding:18px"><div class="tg-section-head"><div><h2>Attendance</h2><p>Recorded school sessions</p></div></div><div style="font-size:38px;font-weight:850;letter-spacing:-1px">{{ $attendancePercent === null ? '—' : $attendancePercent.'%' }}</div><div class="tg-kpi-meta">{{ $attendance && $attendance->total ? ($attendance->present ?: 0).' present out of '.$attendance->total.' recorded sessions' : 'Attendance data will appear here.' }}</div><div class="tg-alert" style="margin-top:18px">Attendance is calculated from the school's recorded attendance data.</div></div>
</section>
<section class="tg-section tg-card" style="padding:18px"><div class="tg-section-head"><div><h2>Results</h2><p>Published examination performance</p></div></div>
@if($results->isEmpty())<div class="tg-empty"><strong>No published results yet</strong><span>Results will appear here after the school publishes them.</span></div>
@else<div style="overflow:auto"><table class="table"><tr><th>Exam</th><th>Subject</th><th>Marks</th><th>Grade</th></tr>@foreach($results as $result)<tr><td>{{ $result->exam_name }}</td><td>{{ $result->subject }}</td><td>{{ $result->marks }}/{{ $result->max_marks }}</td><td>{{ $result->grade ?: '—' }}</td></tr>@endforeach</table></div>@endif</section>
<section class="tg-section tg-two">
<div class="tg-card" style="padding:18px"><div class="tg-section-head"><div><h2>Feedback history</h2><p>Conversations raised with the school</p></div></div>@if($feedback->isEmpty())<div class="tg-empty"><strong>No feedback yet</strong><span>Use the form to contact the school about this student.</span></div>@else<div class="tg-list">@foreach($feedback->take(8) as $item)<div class="tg-list-item"><div><div class="tg-list-title">{{ $item->subject }}</div><div class="tg-list-meta">{{ $item->category_name ?: 'General' }} · {{ $item->created_at }}</div></div><span class="tg-status">{{ ucfirst($item->status) }}</span></div>@endforeach</div>@endif</div>
<div class="tg-card" style="padding:18px"><div class="tg-section-head"><div><h2>Contact school</h2><p>Send a message about {{ $student->name }}</p></div></div><form method="post" action="{{ route('tagore.feedback.submit', $student->id) }}">@csrf<div class="tg-field"><label>Subject</label><input name="subject" required maxlength="150" placeholder="What would you like to discuss?"></div><div class="tg-field" style="margin-top:10px"><label>Message</label><textarea name="message" required maxlength="5000" rows="5" placeholder="Write your message…"></textarea></div><button type="submit" style="margin-top:10px">Send to school</button></form></div>
</section>
</main></div></body></html>