<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{{ $student->name }} · TagoreK12</title>
<style>:root{font-family:Inter,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:#172033;background:#f4f7fb}*{box-sizing:border-box}body{margin:0}.shell{max-width:1100px;margin:auto;padding:24px 16px 60px}.top{display:flex;justify-content:space-between;gap:20px;align-items:center}.brand{font-size:24px;font-weight:800}.muted{color:#64748b;font-size:14px}.btn{display:inline-block;text-decoration:none;background:#172033;color:white;padding:9px 13px;border-radius:9px}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin:20px 0}.card{background:white;border:1px solid #e2e8f0;border-radius:14px;padding:17px}.value{font-size:26px;font-weight:800;margin-top:5px}.section{margin-top:18px}.section h2{font-size:18px;margin:0 0 12px}.table{width:100%;border-collapse:collapse}.table th,.table td{text-align:left;padding:10px;border-bottom:1px solid #edf2f7;font-size:14px}.form input,.form textarea,.form select{width:100%;padding:10px;border:1px solid #cbd5e1;border-radius:8px;margin:6px 0 10px;font:inherit}.form button{border:0;border-radius:9px;padding:10px 15px;background:#172033;color:#fff;cursor:pointer}.success{padding:12px;background:#ecfdf5;border:1px solid #a7f3d0;border-radius:10px;margin:15px 0}@media(max-width:800px){.grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:480px){.grid{grid-template-columns:1fr}.top{align-items:flex-start;flex-direction:column}}
</style></head><body><div class="shell">
<div class="top"><div><div class="brand">{{ $student->name }}</div><div class="muted">{{ $student->institution ?: 'Tagore Institution' }}</div></div><a class="btn" href="{{ route('tagore.dashboard') }}">← Dashboard</a></div>
@if(session('success'))<div class="success">{{ session('success') }}</div>@endif
<div class="grid"><div class="card"><div class="muted">Fees outstanding</div><div class="value">₹{{ number_format($fees->sum('outstanding_amount'),2) }}</div></div><div class="card"><div class="muted">Fees paid</div><div class="value">₹{{ number_format($fees->sum('paid_amount'),2) }}</div></div><div class="card"><div class="muted">Attendance</div><div class="value">{{ $attendancePercent === null ? '—' : $attendancePercent.'%' }}</div><div class="muted">{{ $attendance && $attendance->total ? ($attendance->present ?: 0).' / '.$attendance->total.' present' : '' }}</div></div><div class="card"><div class="muted">Published results</div><div class="value">{{ $results->count() }}</div></div></div>
<div class="section card"><h2>Fees</h2>@if($fees->isEmpty())<div class="muted">No fee obligations recorded yet.</div>@else<table class="table"><tr><th>Due date</th><th>Net</th><th>Paid</th><th>Outstanding</th><th>Status</th></tr>@foreach($fees as $fee)<tr><td>{{ $fee->due_date ?: '—' }}</td><td>₹{{ number_format($fee->net_amount,2) }}</td><td>₹{{ number_format($fee->paid_amount,2) }}</td><td>₹{{ number_format($fee->outstanding_amount,2) }}</td><td>{{ ucfirst($fee->status) }}</td></tr>@endforeach</table>@endif</div>
<div class="section card"><h2>Attendance</h2><div class="muted">{{ $attendancePercent === null ? 'No attendance records available.' : 'Present '.($attendance->present ?: 0).' of '.$attendance->total.' recorded sessions ('.$attendancePercent.'%).' }}</div></div>
<div class="section card"><h2>Results</h2>@if($results->isEmpty())<div class="muted">No published results yet. The prototype uses a simple Tagore result ledger, so Exam Pro is not required.</div>@else<table class="table"><tr><th>Exam</th><th>Subject</th><th>Marks</th><th>Grade</th></tr>@foreach($results as $result)<tr><td>{{ $result->exam_name }}</td><td>{{ $result->subject }}</td><td>{{ $result->marks }}/{{ $result->max_marks }}</td><td>{{ $result->grade ?: '—' }}</td></tr>@endforeach</table>@endif</div>
<div class="section card"><h2>Feedback</h2>@if($feedback->isEmpty())<div class="muted">No feedback submitted yet.</div>@else<table class="table"><tr><th>Subject</th><th>Category</th><th>Status</th><th>Date</th></tr>@foreach($feedback as $item)<tr><td>{{ $item->subject }}</td><td>{{ $item->category_name ?: 'General' }}</td><td>{{ ucfirst($item->status) }}</td><td>{{ $item->created_at }}</td></tr>@endforeach</table>@endif</div>
<div class="section card"><h2>Send feedback</h2><form class="form" method="post" action="{{ route('tagore.feedback.submit', $student->id) }}">@csrf<input name="subject" required maxlength="150" placeholder="Subject"><textarea name="message" required maxlength="5000" rows="4" placeholder="Write your feedback..."></textarea><button type="submit">Submit feedback</button></form></div>
</div></body></html>
