<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>TagoreK12</title>
<style>:root{font-family:Inter,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:#172033;background:#f4f7fb}*{box-sizing:border-box}body{margin:0}.shell{max-width:1180px;margin:auto;padding:28px 18px 60px}.top{display:flex;justify-content:space-between;align-items:center;gap:20px;margin-bottom:20px}.brand{font-size:27px;font-weight:800}.sub,.muted{color:#64748b;font-size:14px}.pill{background:#e8eefc;padding:7px 12px;border-radius:999px;font-size:13px;color:#334155}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin:18px 0}.card{background:white;border:1px solid #e2e8f0;border-radius:14px;padding:18px;box-shadow:0 2px 8px rgba(15,23,42,.04)}.label{color:#64748b;font-size:13px}.value{font-size:30px;font-weight:800;margin-top:7px}.section{margin-top:18px}.section h2{font-size:18px;margin:0 0 12px}.table{width:100%;border-collapse:collapse}.table th,.table td{text-align:left;padding:11px;border-bottom:1px solid #edf2f7;font-size:14px}.table a{text-decoration:none}.nav{display:flex;flex-wrap:wrap;gap:8px;margin:14px 0}.nav a{background:white;border:1px solid #e2e8f0;border-radius:10px;padding:9px 13px;text-decoration:none;color:#334155;font-size:14px}.notice{background:#fff7ed;border:1px solid #fed7aa;border-radius:12px;padding:14px;color:#9a3412;margin-bottom:18px}.feature{display:grid;grid-template-columns:repeat(5,1fr);gap:10px}.feature div{padding:14px;border:1px solid #e2e8f0;border-radius:10px}.feature b{display:block;margin-bottom:4px}@media(max-width:800px){.grid{grid-template-columns:repeat(2,1fr)}.feature{grid-template-columns:repeat(2,1fr)}.top{align-items:flex-start;flex-direction:column}}@media(max-width:480px){.grid{grid-template-columns:1fr}.feature{grid-template-columns:1fr}.shell{padding:20px 12px}}</style></head>
<body><div class="shell">
<div class="top"><div><div class="brand">TagoreK12</div><div class="sub">One unified application for the Tagore Group</div></div><div class="pill">{{ $roles->implode(', ') ?: 'GegoK12 user' }}</div></div>
<div class="notice">Prototype mode — GegoK12 remains the underlying school-management foundation. This Tagore layer adds the Group experience without requiring Fee Pro or Exam Pro.</div>
<div class="nav"><a href="{{ route('tagore.dashboard') }}">Home</a>@if($roles->contains('PARENT'))<a href="{{ route('tagore.parent.dashboard') }}">Parent Dashboard</a>@endif<a href="{{ url('/dashboard') }}">GegoK12</a>@if($roles->intersect(['OWNER','PRINCIPAL','COORDINATOR'])->isNotEmpty())<a href="{{ route('tagore.admissions.index') }}">Admissions CRM</a>@endif @if($roles->intersect(['OWNER','PRINCIPAL','COORDINATOR','TEACHER','ACCOUNTS'])->isNotEmpty())<a href="{{ route('tagore.tasks.index') }}">Work Tasks</a>@endif<a href="{{ route('tagore.dashboard.api') }}">API</a></div>
<div class="grid"><div class="card"><div class="label">Institutions</div><div class="value">{{ $stats['institutions'] }}</div></div><div class="card"><div class="label">My children</div><div class="value">{{ $stats['children'] }}</div></div><div class="card"><div class="label">Outstanding fee items</div><div class="value">{{ $stats['pending_fees'] }}</div></div><div class="card"><div class="label">Open feedback</div><div class="value">{{ $stats['open_feedback'] }}</div></div></div>
@if($roles->intersect(['OWNER','PRINCIPAL','COORDINATOR','TEACHER','ACCOUNTS'])->isNotEmpty())<div class="section card"><h2>Work Management</h2><div class="feature"><div><b>{{ $stats['open_tasks'] ?? 0 }}</b><span class="muted">Open tasks</span></div><div><b>{{ $stats['overdue_tasks'] ?? 0 }}</b><span class="muted">Overdue tasks</span></div><div><b>Assignments</b><span class="muted">Create & track employee work</span></div><div><b>Progress</b><span class="muted">0–100% completion</span></div><div><a href="{{ route('tagore.tasks.index') }}">Open task board →</a></div></div></div>@endif
<div class="section card"><h2>Institutions</h2>@if($institutions->isEmpty())<div class="muted">No Tagore institutions linked yet. Run the prototype seeder after GegoK12 has at least one school.</div>@else<table class="table"><tr><th>Code</th><th>Institution</th><th>GegoK12 school</th></tr>@foreach($institutions as $institution)<tr><td>{{ $institution->code }}</td><td>{{ $institution->display_name }}</td><td>{{ $institution->school_name }}</td></tr>@endforeach</table>@endif</div>
<div class="section card"><h2>My children</h2>@if($children->isEmpty())<div class="muted">No parent-child relationship is linked to this account yet.</div>@else<table class="table"><tr><th>Student</th><th>Relationship</th><th></th></tr>@foreach($children as $child)<tr><td><a href="{{ route('tagore.child', $child->student_id) }}">{{ $child->name }}</a></td><td>{{ $child->relationship ?: 'Guardian' }}</td><td><a href="{{ route('tagore.child', $child->student_id) }}">Open →</a></td></tr>@endforeach</table>@endif</div>
<div class="section card"><h2>Phase 1 in one application</h2><div class="feature"><div><b>Fees</b><span class="muted">Ledger & outstanding</span></div><div><b>Attendance</b><span class="muted">Live GegoK12 data</span></div><div><b>Results</b><span class="muted">Published results</span></div><div><b>Feedback</b><span class="muted">Submit & track</span></div><div><b>Notices</b><span class="muted">Existing communication</span></div></div></div>
</div></body></html>
