@php use Illuminate\Support\Str; @endphp
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{{ $employee->name }} | TagoreK12</title>
<style>body{font-family:system-ui,-apple-system,sans-serif;margin:0;background:#f4f7fb;color:#172033}.shell{max-width:1200px;margin:auto;padding:24px 16px 60px}.card{background:#fff;border:1px solid #e2e8f0;border-radius:12px;padding:16px;margin-top:16px}.grid{display:grid;grid-template-columns:repeat(5,1fr);gap:12px}.metric b{display:block;font-size:27px}.muted{color:#64748b;font-size:13px}table{width:100%;border-collapse:collapse;margin-top:10px}th,td{padding:9px;border-bottom:1px solid #edf2f7;text-align:left;font-size:13px}a{color:#2563eb;text-decoration:none}.tag{display:inline-block;padding:3px 7px;border-radius:999px;background:#eef2ff;font-size:12px}@media(max-width:850px){.grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:500px){.grid{grid-template-columns:1fr}}</style></head>
<body><div class="shell"><p><a href="{{ route('tagore.tasks.index') }}">← Work Tasks</a></p>
<div class="card"><h1 style="margin:0 0 6px">{{ $employee->name }}</h1><div class="muted">{{ $employee->designation ?: 'Staff' }} · {{ $employee->department ?: 'No department' }} · {{ $employee->role }}</div><div class="muted">{{ $employee->email }}</div></div>
<div class="grid"><div class="card metric"><span class="muted">Assigned</span><b>{{ $taskStats['assigned'] }}</b></div><div class="card metric"><span class="muted">Active</span><b>{{ $taskStats['active'] }}</b></div><div class="card metric"><span class="muted">Completed</span><b>{{ $taskStats['completed'] }}</b></div><div class="card metric"><span class="muted">Overdue</span><b>{{ $taskStats['overdue'] }}</b></div><div class="card metric"><span class="muted">Completion</span><b>{{ $taskStats['completion_rate'] }}%</b></div></div>
<div class="card"><h2>Workload position</h2><p>Active workload: <b>{{ $taskStats['active'] }}</b> · Team average: <b>{{ $teamAverageActive }}</b> active tasks per staff.</p><p class="muted">This is a workload comparison, not a performance rating.</p></div>
<div class="card"><h2>7 / 30 / 90-day trend</h2><table><tr><th>Window</th><th>Tasks created</th><th>Tasks completed</th><th>Net</th></tr>@foreach($trend as $days=>$values)<tr><td>{{ $days }} days</td><td>{{ $values['created'] }}</td><td>{{ $values['completed'] }}</td><td>{{ $values['created']-$values['completed'] }}</td></tr>@endforeach</table></div>
<div class="card"><h2>Assigned work</h2><table><tr><th>Task</th><th>Status</th><th>Progress</th><th>Priority</th><th>Due</th></tr>@forelse($tasks as $task)<tr><td>{{ $task->title }}</td><td><span class="tag">{{ ucfirst(str_replace('_',' ',$task->status)) }}</span></td><td>{{ $task->progress }}%</td><td>{{ ucfirst($task->priority) }}</td><td>{{ $task->due_at ? date('d M Y H:i',strtotime($task->due_at)) : '—' }}</td></tr>@empty<tr><td colspan="5">No assigned tasks.</td></tr>@endforelse</table></div>
<div class="card"><h2>Manager review history</h2><table><tr><th>Date</th><th>Task</th><th>Type</th><th>Outcome</th><th>Manager</th><th>Follow-up</th><th>Notes</th></tr>@forelse($reviews as $review)<tr><td>{{ date('d M Y H:i',strtotime($review->created_at)) }}</td><td>{{ $review->task_title ?: '—' }}</td><td>{{ ucfirst(str_replace('_',' ',$review->review_type)) }}</td><td>{{ ucfirst(str_replace('_',' ',$review->outcome)) }}</td><td>{{ $review->manager_name }}</td><td>{{ $review->follow_up_at ? ($review->completed_at ? 'Closed' : date('d M Y H:i',strtotime($review->follow_up_at))) : '—' }}</td><td>{{ Str::limit($review->notes,140) }}</td></tr>@empty<tr><td colspan="7">No reviews recorded.</td></tr>@endforelse</table></div>
<div class="card"><h2>Activity timeline</h2><table><tr><th>Time</th><th>Event</th><th>Task</th><th>Actor</th></tr>@forelse($activity as $event)<tr><td>{{ date('d M Y H:i',strtotime($event->created_at)) }}</td><td>{{ ucfirst(str_replace('_',' ',$event->event_type)) }}</td><td>{{ $event->task_title ?: '—' }}</td><td>{{ $event->actor_name ?: 'System' }}</td></tr>@empty<tr><td colspan="4">No activity recorded.</td></tr>@endforelse</table></div>
</div></body></html>