@php use Illuminate\Support\Str; @endphp
<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Tasks | TagoreK12</title>
<style>
body{font-family:system-ui,-apple-system,sans-serif;margin:0;background:#f4f7fb;color:#172033}.shell{max-width:1200px;margin:auto;padding:24px 16px 60px}.cards{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.card{background:#fff;border:1px solid #e2e8f0;border-radius:12px;padding:16px}.v{font-size:28px;font-weight:800}form{display:flex;gap:8px;flex-wrap:wrap}input,select,textarea,button{padding:9px;border:1px solid #cbd5e1;border-radius:8px;background:#fff;font:inherit}textarea{min-height:80px;width:100%}.new{margin-top:16px}.new .row{display:grid;grid-template-columns:1fr 1fr 1fr 1fr;gap:8px}.new .wide{grid-column:1/-1}table{width:100%;background:#fff;border-collapse:collapse;margin-top:16px}th,td{padding:10px;border-bottom:1px solid #edf2f7;text-align:left;font-size:14px}a{text-decoration:none;color:#2563eb}.muted{color:#64748b}@media(max-width:800px){.cards{grid-template-columns:repeat(2,1fr)}.new .row{grid-template-columns:1fr 1fr}}@media(max-width:500px){.cards{grid-template-columns:1fr}.new .row{grid-template-columns:1fr}}
</style></head><body><div class="shell">
<p><a href="{{ route('tagore.dashboard') }}">← Dashboard</a></p><h1>Work Tasks</h1><p class="muted">Lightweight employee work assignment and progress tracking. No secondary application or heavy frontend.</p>
<div class="cards">@foreach([['Open','open'],['Due today','due_today'],['Overdue','overdue'],['Completed','completed']] as [$l,$k])<div class="card"><small>{{ $l }}</small><div class="v">{{ $stats[$k] }}</div></div>@endforeach</div>
<div class="card" style="margin-top:16px"><h3 style="margin-top:0">Institution workload</h3><form method="get" style="margin-bottom:10px"><select name="institution_id" onchange="this.form.submit()"><option value="">All visible institutions</option>@foreach($institutions as $institution)<option value="{{ $institution->id }}" @selected($selectedInstitutionId===$institution->id)>{{ $institution->display_name }}</option>@endforeach</select><input type="hidden" name="q" value="{{ request('q') }}"><input type="hidden" name="status" value="{{ request('status') }}"><input type="hidden" name="assigned_to" value="{{ request('assigned_to') }}"><input type="hidden" name="department_id" value="{{ request('department_id') }}"></form><div style="overflow:auto"><table style="margin-top:0"><tr><th>Employee</th><th>Active</th><th>Due today</th><th>Overdue</th><th>Completed</th><th>Total</th></tr>@forelse($workload as $person)<tr><td><a href="{{ route('tagore.tasks.employee', $person->id) }}"><b>{{ $person->name }}</b></a></td><td>{{ $person->active }}</td><td>{{ $person->due_today }}</td><td>{{ $person->overdue }}</td><td>{{ $person->completed }}</td><td>{{ $person->total }}</td></tr>@empty<tr><td colspan="6">No active employees found in this institution scope.</td></tr>@endforelse @if(($unassignedWorkload->total ?? 0) > 0)<tr><td><a href="{{ request()->fullUrlWithQuery(['assigned_to' => 'unassigned']) }}"><b>Unassigned</b></a></td><td>{{ $unassignedWorkload->active }}</td><td>—</td><td>{{ $unassignedWorkload->overdue }}</td><td>{{ $unassignedWorkload->completed }}</td><td>{{ $unassignedWorkload->total }}</td></tr>@endif</table></div></div>
<div class="card" style="margin-top:16px"><h3 style="margin-top:0">Department workload</h3><div style="overflow:auto"><table style="margin-top:0"><tr><th>Department</th><th>Active</th><th>Overdue</th><th>Blocked</th><th>Completed</th><th>Total</th></tr>@forelse($departmentWorkload as $dept)<tr><td><a href="{{ request()->fullUrlWithQuery(['department_id' => $dept->id]) }}"><b>{{ $dept->name }}</b></a></td><td>{{ $dept->active }}</td><td>{{ $dept->overdue }}</td><td>{{ $dept->blocked }}</td><td>{{ $dept->completed }}</td><td>{{ $dept->total }}</td></tr>@empty<tr><td colspan="6">No departments configured.</td></tr>@endforelse</table></div></div>@if($roles->intersect(['OWNER','PRINCIPAL','COORDINATOR'])->isNotEmpty())
<div class="card new"><h3>Recurring task templates</h3><p class="muted">Automatically create routine work on a daily, weekly or monthly schedule.</p>
<form method="post" action="{{ route('tagore.task-templates.store') }}"><div class="row">
<select name="institution_id" required>@foreach($institutions as $institution)<option value="{{ $institution->id }}">{{ $institution->display_name }}</option>@endforeach</select>
<select name="assigned_to"><option value="">Unassigned</option>@foreach($assignees as $user)<option value="{{ $user->id }}">{{ $user->name }}</option>@endforeach</select>
<select name="department_id"><option value="">Department from assignee</option>@foreach($departments as $department)<option value="{{ $department->id }}">{{ $department->name }}</option>@endforeach</select>
<select name="priority"><option value="normal">Normal</option><option value="low">Low</option><option value="high">High</option><option value="urgent">Urgent</option></select>
<input name="title" placeholder="Recurring task title" required>
<select name="frequency"><option value="daily">Daily</option><option value="weekly">Weekly</option><option value="monthly">Monthly</option></select>
<select name="day_of_week"><option value="">Weekly day</option><option value="1">Monday</option><option value="2">Tuesday</option><option value="3">Wednesday</option><option value="4">Thursday</option><option value="5">Friday</option><option value="6">Saturday</option><option value="0">Sunday</option></select>
<input type="number" name="day_of_month" min="1" max="28" placeholder="Monthly day (1-28)">
<input type="time" name="run_at" value="09:00" required>
<input type="number" name="due_after_minutes" min="1" max="10080" placeholder="Due after minutes">
<textarea class="wide" name="description" placeholder="Instructions for each generated task"></textarea>
</div><button type="submit">Create recurring template</button></form>
@if($templates->isNotEmpty())<table><tr><th>Template</th><th>Schedule</th><th>Assignee</th><th>Next run</th><th>Status</th><th>Action</th></tr>@foreach($templates as $template)<tr>
<td><b>{{ $template->title }}</b><br><span class="muted">{{ $template->department_name ?: 'No department' }}</span></td>
<td>{{ ucfirst($template->frequency) }} at {{ substr($template->run_at,0,5) }}</td><td>{{ $template->assignee_name ?: 'Unassigned' }}</td>
<td>{{ $template->next_run_at ? date('d M Y H:i',strtotime($template->next_run_at)) : '—' }}</td><td>{{ $template->active ? 'Active' : 'Paused' }}</td>
<td><form method="post" action="{{ route('tagore.task-templates.toggle',$template->id) }}">@csrf @method('PATCH')<button>{{ $template->active ? 'Pause' : 'Activate' }}</button></form></td>
</tr>@endforeach</table>@endif</div>
@endif
<div class="card new"><h3>Assign work</h3><form method="post" action="{{ route('tagore.tasks.store') }}">@csrf<div class="row"><select name="institution_id" required>@foreach($institutions as $institution)<option value="{{ $institution->id }}">{{ $institution->display_name }}</option>@endforeach</select><select name="assigned_to"><option value="">Unassigned</option>@foreach($assignees as $user)<option value="{{ $user->id }}">{{ $user->name }}</option>@endforeach</select><select name="department_id"><option value="">Department from assignee</option>@foreach($departments as $department)<option value="{{ $department->id }}" @selected(request('department_id') == $department->id)>{{ $department->name }}</option>@endforeach</select><select name="priority"><option value="normal">Normal</option><option value="low">Low</option><option value="high">High</option><option value="urgent">Urgent</option></select><input type="datetime-local" name="due_at"></div><div class="row" style="margin-top:8px"><input class="wide" name="title" placeholder="Task title" required></div><div class="row" style="margin-top:8px"><textarea class="wide" name="description" placeholder="Expected output / instructions"></textarea></div><button style="margin-top:8px">Create task</button></form></div>
<form method="get" style="margin-top:16px"><input type="hidden" name="institution_id" value="{{ $selectedInstitutionId }}"><input type="hidden" name="department_id" value="{{ request('department_id') }}"><input type="hidden" name="assigned_to" value="{{ request('assigned_to') }}"><input name="q" value="{{ request('q') }}" placeholder="Search tasks"><select name="status"><option value="">All status</option>@foreach(['open','in_progress','blocked','completed','cancelled'] as $s)<option value="{{ $s }}" @selected(request('status')===$s)>{{ ucfirst(str_replace('_',' ',$s)) }}</option>@endforeach</select><button>Filter</button></form>
@if($roles->intersect(['OWNER','PRINCIPAL','COORDINATOR'])->isNotEmpty())<div class="card" style="margin-top:16px"><h3 style="margin-top:0">Manager reviews</h3>@if($managerReviews->isEmpty())<div class="muted">No manager reviews recorded yet.</div>@else<div style="overflow:auto"><table style="margin-top:0"><tr><th>Date</th><th>Employee</th><th>Task</th><th>Outcome</th><th>Manager</th><th>Notes</th><th>Follow-up</th></tr>@foreach($managerReviews as $review)<tr><td>{{ date('d M Y H:i', strtotime($review->created_at)) }}</td><td>{{ $review->employee_name }}</td><td>{{ $review->task_title ?: '—' }}</td><td>{{ ucfirst(str_replace('_',' ',$review->outcome)) }}</td><td>{{ $review->manager_name }}</td><td>{{ Str::limit($review->notes,120) }}</td><td>{{ $review->follow_up_at ? date('d M Y H:i', strtotime($review->follow_up_at)) : '—' }}</td></tr>@endforeach</table></div>@endif</div>@endif
<div class="card" style="margin-top:16px"><h3 style="margin-top:0">Recent activity</h3>@if($recentActivity->isEmpty())<div class="muted">No task activity recorded yet.</div>@else<div style="overflow:auto"><table style="margin-top:0"><tr><th>Time</th><th>Task</th><th>Event</th><th>Actor</th></tr>@foreach($recentActivity as $event)<tr><td>{{ date('d M Y H:i', strtotime($event->created_at)) }}</td><td>{{ $event->task_title }}</td><td>{{ ucfirst(str_replace('_',' ',$event->event_type)) }}</td><td>{{ $event->actor_name ?: 'System' }}</td></tr>@endforeach</table></div>@endif</div>
<table><tr><th>Task</th><th>Department</th><th>Assignee</th><th>Priority</th><th>Status</th><th>Progress</th><th>Due</th>@if($roles->intersect(['OWNER','PRINCIPAL','COORDINATOR'])->isNotEmpty())<th>Review</th>@endif<th>Update</th></tr>@forelse($tasks as $task)<tr><td><b>{{ $task->title }}</b><br><span class="muted">{{ Str::limit($task->description,100) }}</span></td><td>{{ optional($departments->firstWhere('id', $task->department_id))->name ?: '—' }}</td><td>{{ $task->assigned_to ? optional($assignees->firstWhere('id', $task->assigned_to))->name : 'Unassigned' }}</td><td>{{ ucfirst($task->priority) }}</td><td>{{ ucfirst(str_replace('_',' ',$task->status)) }}</td><td>{{ $task->progress }}%</td><td>{{ optional($task->due_at)->format('d M Y H:i') ?: '—' }}</td>@if($roles->intersect(['OWNER','PRINCIPAL','COORDINATOR'])->isNotEmpty())<td><form method="post" action="{{ route('tagore.tasks.review',$task->id) }}"><details><summary>Review</summary>@csrf<select name="review_type"><option value="follow_up">Follow-up</option><option value="performance">Performance</option><option value="recognition">Recognition</option><option value="corrective">Corrective</option></select><select name="outcome"><option value="note">Note</option><option value="positive">Positive</option><option value="needs_attention">Needs attention</option><option value="action_required">Action required</option></select><textarea name="notes" placeholder="Manager review note" required></textarea><label><input type="checkbox" name="action_required" value="1"> Action required</label><input type="datetime-local" name="follow_up_at"><button>Record review</button></details></form></td>@endif<td><form method="post" action="{{ route('tagore.tasks.update',$task->id) }}">@csrf @method('PATCH')<select name="status">@foreach(['open','in_progress','blocked','completed','cancelled'] as $s)<option value="{{ $s }}" @selected($task->status===$s)>{{ ucfirst(str_replace('_',' ',$s)) }}</option>@endforeach</select><select name="assigned_to"><option value="">Unassigned</option>@foreach($assignees as $user)<option value="{{ $user->id }}" @selected((int)$task->assigned_to === (int)$user->id)>{{ $user->name }}</option>@endforeach</select><select name="department_id"><option value="">No department</option>@foreach($departments as $department)<option value="{{ $department->id }}" @selected((int)$task->department_id === (int)$department->id)>{{ $department->name }}</option>@endforeach</select><input name="progress" type="number" min="0" max="100" value="{{ $task->progress }}" style="width:65px"><button>Save</button></form></td></tr>@empty<tr><td colspan="9">No tasks found.</td></tr>@endforelse</table><div>{{ $tasks->links() }}</div>
</div></body></html>
