[Reading 17 lines from start (total: 17 lines, 0 remaining)]

@extends('layouts.app')
@section('base-content')
<link rel="stylesheet" href="{{ asset('tagore-erp.css') }}">
<div class="tg-app"><div class="tg-shell">
<header class="tg-topbar"><div class="tg-brand"><div class="tg-logo">T</div><div><strong>TagoreK12</strong><span>Learning, Hostel & Store</span></div></div><a class="tg-btn" href="{{ route('tagore.dashboard') }}">ERP Home</a></header>
@if(session('success'))<div class="tg-alert success">{{ session('success') }}</div>@endif
@if($errors->any())<div class="tg-alert danger">{{ $errors->first() }}</div>@endif
<section class="tg-hero"><div><span class="tg-eyebrow">Campus Services</span><h1>Learning, Hostel & Student Store</h1><p>Course publishing, content, surveys, hostel allocation and store stock/orders.</p></div></section>
<section class="tg-card"><h2>Hostel room</h2><form class="tg-form" method="POST" action="{{ route('tagore.learning.room') }}">@csrf<div class="tg-grid"><label class="tg-field"><span>Institution</span><select name="institution_id">@foreach($institutions as $i)<option value="{{ $i->id }}">{{ $i->display_name }}</option>@endforeach</select></label><label class="tg-field"><span>Hostel</span><input name="hostel_name" required></label><label class="tg-field"><span>Room</span><input name="room_no" required></label><label class="tg-field"><span>Beds</span><input type="number" name="beds" min="1" value="1"></label><label class="tg-field"><span>Fee</span><input type="number" name="fee" step="0.01" value="0"></label></div><button class="tg-btn primary">Create room</button></form></section>
<section class="tg-card"><h2>Allocate hostel bed</h2><form class="tg-form" method="POST" action="{{ route('tagore.learning.allocate') }}">@csrf<div class="tg-grid"><label class="tg-field"><span>Room</span><select name="room_id">@foreach($rooms as $r)<option value="{{ $r->id }}">{{ $r->hostel_name }} / {{ $r->room_no }} ({{ $r->beds }} beds)</option>@endforeach</select></label><label class="tg-field"><span>Student ID</span><input type="number" name="student_id" required></label><label class="tg-field"><span>Bed</span><input name="bed_no" required></label><label class="tg-field"><span>Check-in</span><input type="date" name="check_in" value="{{ today()->toDateString() }}"></label></div><button class="tg-btn primary">Allocate</button></form></section>
<section class="tg-card"><h2>Course</h2><form class="tg-form" method="POST" action="{{ route('tagore.learning.course') }}">@csrf<div class="tg-grid"><label class="tg-field"><span>Institution</span><select name="institution_id">@foreach($institutions as $i)<option value="{{ $i->id }}">{{ $i->display_name }}</option>@endforeach</select></label><label class="tg-field"><span>Title</span><input name="title" required></label><label class="tg-field"><span>Code</span><input name="code"></label><label class="tg-field"><span>Grade range</span><input name="grade_range"></label><label class="tg-field"><span>Capacity</span><input name="capacity" type="number" min="0" value="0"></label><label class="tg-field"><span>Fee</span><input name="fee" type="number" step="0.01" value="0"></label><label class="tg-field" style="grid-column:1/-1"><span>Description</span><textarea name="description"></textarea></label></div><button class="tg-btn primary">Create course</button></form></section>
<section class="tg-card"><h2>Learning content</h2><form class="tg-form" method="POST" action="{{ route('tagore.learning.content') }}">@csrf<div class="tg-grid"><label class="tg-field"><span>Institution</span><select name="institution_id">@foreach($institutions as $i)<option value="{{ $i->id }}">{{ $i->display_name }}</option>@endforeach</select></label><label class="tg-field"><span>Title</span><input name="title" required></label><label class="tg-field"><span>Type</span><input name="content_type" value="video"></label><label class="tg-field"><span>Path / URL</span><input name="path"></label><label class="tg-field"><span>Grade range</span><input name="grade_range"></label><label class="tg-field"><span>Subject</span><input name="subject"></label><label class="tg-field"><span>Access JSON</span><input name="access_json" placeholder='{"roles":["STUDENT"]}'></label></div><button class="tg-btn primary">Publish content</button></form></section>
<section class="tg-card"><h2>Survey / feedback</h2><form class="tg-form" method="POST" action="{{ route('tagore.learning.survey') }}">@csrf<div class="tg-grid"><label class="tg-field"><span>Institution</span><select name="institution_id">@foreach($institutions as $i)<option value="{{ $i->id }}">{{ $i->display_name }}</option>@endforeach</select></label><label class="tg-field"><span>Title</span><input name="title" required></label><label class="tg-field" style="grid-column:1/-1"><span>Questions JSON</span><textarea name="questions_json" placeholder='[{"id":"q1","text":"How was the class?","type":"rating"}]'></textarea></label><label class="tg-field"><span>Anonymous</span><input type="checkbox" name="anonymous" value="1"></label></div><button class="tg-btn primary">Publish survey</button></form></section>
<section class="tg-card"><h2>Store product</h2><form class="tg-form" method="POST" action="{{ route('tagore.learning.product') }}">@csrf<div class="tg-grid"><label class="tg-field"><span>Institution</span><select name="institution_id">@foreach($institutions as $i)<option value="{{ $i->id }}">{{ $i->display_name }}</option>@endforeach</select></label><label class="tg-field"><span>Name</span><input name="name" required></label><label class="tg-field"><span>SKU</span><input name="sku" required></label><label class="tg-field"><span>Category</span><input name="category"></label><label class="tg-field"><span>Price</span><input name="price" type="number" step="0.01" min="0"></label><label class="tg-field"><span>Stock</span><input name="stock" type="number" min="0"></label></div><button class="tg-btn primary">Add product</button></form></section>
<section class="tg-card"><h2>Current catalogue</h2><div class="tg-table-wrap"><table><thead><tr><th>Product</th><th>SKU</th><th>Price</th><th>Stock</th></tr></thead><tbody>@foreach($products as $p)<tr><td>{{ $p->name }}</td><td>{{ $p->sku }}</td><td>₹{{ number_format($p->price,2) }}</td><td>{{ $p->stock }}</td></tr>@endforeach</tbody></table></div></section>
</div></div>
@endsection

[executed on device: DESKTOP-564ES39 (d76c0fdf-a9a5-457e-b21a-81313e01406e)]