@extends('layouts.app')
@section('base-content')
<link rel="stylesheet" href="{{ asset('tagore-erp.css') }}">
<div class="tg-app"><div class="tg-shell">
<header class="tg-topbar"><div class="tg-brand"><div class="tg-logo">T</div><div><strong>TagoreK12</strong><span>Security & Gate Pass</span></div></div><a class="tg-btn" href="{{ route('tagore.dashboard') }}">ERP Home</a></header>
@if(session('success'))<div class="tg-alert success">{{ session('success') }}</div>@endif
@if($errors->any())<div class="tg-alert danger">{{ $errors->first() }}</div>@endif
<section class="tg-hero"><div><span class="tg-eyebrow">Campus Security</span><h1>Visitors & Gate Passes</h1><p>OTP visitor verification, approval workflow, expiring pass tokens and an audit trail.</p></div></section>
<section class="tg-card"><h2>Register visitor</h2><form class="tg-form" method="POST" action="{{ route('tagore.security.visitor') }}">@csrf<div class="tg-grid"><label class="tg-field"><span>Institution</span><select name="institution_id" required>@foreach($institutions as $i)<option value="{{ $i->id }}">{{ $i->display_name }}</option>@endforeach</select></label><label class="tg-field"><span>Visitor name</span><input name="visitor_name" required></label><label class="tg-field"><span>Phone</span><input name="phone"></label><label class="tg-field"><span>Purpose</span><input name="purpose" required></label><label class="tg-field"><span>Host user ID</span><input name="host_user_id" type="number"></label></div><button class="tg-btn primary">Register visitor</button></form></section>
<section class="tg-card"><h2>Visitor log</h2><div class="tg-table-wrap"><table><thead><tr><th>Name</th><th>Purpose</th><th>Status</th><th>OTP check-in</th><th>Action</th></tr></thead><tbody>@foreach($visitors as $v)<tr><td>{{ $v->visitor_name }}</td><td>{{ $v->purpose }}</td><td>{{ $v->status }}</td><td>@if($v->status==='expected')<form method="POST" action="{{ route('tagore.security.visitor.checkin',$v->id) }}" style="display:inline">@csrf<input name="otp" placeholder="6 digit OTP" required><button class="tg-btn">Check in</button></form>@endif</td><td>@if($v->status==='checked_in')<form method="POST" action="{{ route('tagore.security.visitor.checkout',$v->id) }}" style="display:inline">@csrf<button class="tg-btn primary">Check out</button></form>@endif</td></tr>@endforeach</tbody></table></div></section>
<section class="tg-card"><h2>Create gate pass</h2><form class="tg-form" method="POST" action="{{ route('tagore.security.gatepass') }}">@csrf<div class="tg-grid"><label class="tg-field"><span>Institution</span><select name="institution_id" required>@foreach($institutions as $i)<option value="{{ $i->id }}">{{ $i->display_name }}</option>@endforeach</select></label><label class="tg-field"><span>Student ID</span><input name="student_id" type="number" required></label><label class="tg-field"><span>Pass type</span><input name="pass_type" value="leave"></label><label class="tg-field"><span>Valid from</span><input name="valid_from" type="datetime-local" required></label><label class="tg-field"><span>Valid until</span><input name="valid_until" type="datetime-local" required></label><label class="tg-field" style="grid-column:1/-1"><span>Reason</span><textarea name="reason" required></textarea></label></div><button class="tg-btn primary">Request gate pass</button></form></section>
<section class="tg-card"><h2>Gate passes</h2><div class="tg-table-wrap"><table><thead><tr><th>Student</th><th>Type</th><th>Validity</th><th>Status</th><th>Action</th></tr></thead><tbody>@foreach($passes as $p)<tr><td>{{ $p->student_id }}</td><td>{{ $p->pass_type }}</td><td>{{ $p->valid_from }} → {{ $p->valid_until }}</td><td>{{ $p->status }}</td><td>@if($p->status==='pending')<form method="POST" action="{{ route('tagore.security.gatepass.decide',$p->id) }}" style="display:inline">@csrf @method('PATCH')<input type="hidden" name="decision" value="approved"><button class="tg-btn">Approve</button></form><form method="POST" action="{{ route('tagore.security.gatepass.decide',$p->id) }}" style="display:inline">@csrf @method('PATCH')<input type="hidden" name="decision" value="rejected"><button class="tg-btn danger">Reject</button></form>@endif</td></tr>@endforeach</tbody></table></div></section>
<section class="tg-card"><h2>Security events</h2><div class="tg-table-wrap"><table><thead><tr><th>Type</th><th>Subject</th><th>When</th><th>Actor</th></tr></thead><tbody>@foreach($events as $e)<tr><td>{{ $e->event_type }}</td><td>{{ $e->subject_type }} #{{ $e->subject_id }}</td><td>{{ $e->created_at }}</td><td>{{ $e->actor_user_id }}</td></tr>@endforeach</tbody></table></div></section>
</div></div>
@endsection
