@extends('layouts.app')
@section('content')
<link rel="stylesheet" href="{{ asset('tagore-erp.css') }}">
<div class="tg-app"><div class="tg-shell">
<header class="tg-topbar"><div class="tg-brand"><div class="tg-logo">T</div><div><strong>TagoreK12</strong><span>Inventory & Finance</span></div></div><a class="tg-btn" href="{{ route('tagore.dashboard') }}">ERP Home</a></header>
@if(session('success'))<div class="tg-alert success">{{ session('success') }}</div>@endif
@if($errors->any())<div class="tg-alert danger">{{ $errors->first() }}</div>@endif
<section class="tg-hero"><div><span class="tg-eyebrow">Operations</span><h1>Inventory, Procurement & Expenses</h1><p>Vendors, stock, purchase orders, assets and approval-controlled department expenses.</p></div></section>
<section class="tg-card"><h2>Add vendor</h2><form class="tg-form" method="POST" action="{{ route('tagore.inventory.vendor') }}">@csrf<div class="tg-grid"><label class="tg-field"><span>Institution</span><select name="institution_id" required>@foreach($institutions as $i)<option value="{{ $i->id }}">{{ $i->display_name }}</option>@endforeach</select></label><label class="tg-field"><span>Name</span><input name="name" required></label><label class="tg-field"><span>Phone</span><input name="phone"></label><label class="tg-field"><span>Email</span><input name="email" type="email"></label><label class="tg-field"><span>GSTIN</span><input name="gstin"></label><label class="tg-field"><span>Address</span><input name="address"></label></div><button class="tg-btn primary">Add vendor</button></form></section>
<section class="tg-card"><h2>Add inventory item</h2><form class="tg-form" method="POST" action="{{ route('tagore.inventory.item') }}">@csrf<div class="tg-grid"><label class="tg-field"><span>Institution</span><select name="institution_id" required>@foreach($institutions as $i)<option value="{{ $i->id }}">{{ $i->display_name }}</option>@endforeach</select></label><label class="tg-field"><span>Name</span><input name="name" required></label><label class="tg-field"><span>SKU</span><input name="sku"></label><label class="tg-field"><span>Category</span><input name="category"></label><label class="tg-field"><span>Unit</span><input name="unit" value="pcs"></label><label class="tg-field"><span>Reorder level</span><input name="reorder_level" type="number" step="0.001" value="0"></label><label class="tg-field"><span>Unit cost</span><input name="unit_cost" type="number" step="0.01" value="0"></label><label class="tg-field"><span>Vendor</span><select name="vendor_id"><option value="">—</option>@foreach($vendors as $v)<option value="{{ $v->id }}">{{ $v->name }}</option>@endforeach</select></label></div><button class="tg-btn primary">Add item</button></form></section>
<section class="tg-card"><h2>Stock movement</h2><form class="tg-form" method="POST" action="{{ route('tagore.inventory.movement') }}">@csrf<div class="tg-grid"><label class="tg-field"><span>Institution</span><select name="institution_id" required>@foreach($institutions as $i)<option value="{{ $i->id }}">{{ $i->display_name }}</option>@endforeach</select></label><label class="tg-field"><span>Item</span><select name="item_id" required>@foreach($items as $item)<option value="{{ $item->id }}">{{ $item->name }} ({{ $item->quantity }})</option>@endforeach</select></label><label class="tg-field"><span>Movement</span><select name="type"><option value="in">Stock in</option><option value="out">Stock out</option><option value="adjust">Set quantity</option></select></label><label class="tg-field"><span>Quantity</span><input name="quantity" type="number" step="0.001" min="0.001" required></label><label class="tg-field"><span>Notes</span><input name="notes"></label></div><button class="tg-btn primary">Record movement</button></form></section>
<section class="tg-card"><h2>Purchase order</h2><form class="tg-form" method="POST" action="{{ route('tagore.inventory.po') }}">@csrf<div class="tg-grid"><label class="tg-field"><span>Institution</span><select name="institution_id" required>@foreach($institutions as $i)<option value="{{ $i->id }}">{{ $i->display_name }}</option>@endforeach</select></label><label class="tg-field"><span>Vendor</span><select name="vendor_id" required>@foreach($vendors as $v)<option value="{{ $v->id }}">{{ $v->name }}</option>@endforeach</select></label><label class="tg-field" style="grid-column:1/-1"><span>Items JSON</span><textarea name="items_json" rows="5" placeholder='[{"item_id":1,"quantity":10,"unit_cost":125}]'></textarea></label></div><button class="tg-btn primary">Create PO</button></form>
<div class="tg-table-wrap"><table><thead><tr><th>PO</th><th>Status</th><th>Total</th><th>Actions</th></tr></thead><tbody>@foreach($orders as $po)<tr><td>{{ $po->po_no }}</td><td>{{ $po->status }}</td><td>₹{{ number_format($po->total_amount,2) }}</td><td>@if($po->status==='draft')<form method="POST" action="{{ route('tagore.inventory.po.approve',$po->id) }}" style="display:inline">@csrf @method('PATCH')<button class="tg-btn">Approve</button></form>@elseif(in_array($po->status,['approved','partial']))<form method="POST" action="{{ route('tagore.inventory.po.receive',$po->id) }}" style="display:inline">@csrf @method('PATCH')<button class="tg-btn primary">Receive</button></form>@endif</td></tr>@endforeach</tbody></table></div></section>
<section class="tg-card"><h2>Expense approvals</h2><div class="tg-table-wrap"><table><thead><tr><th>Date</th><th>Department</th><th>Category</th><th>Amount</th><th>Status</th><th>Action</th></tr></thead><tbody>@foreach($expenses as $e)<tr><td>{{ $e->expense_date }}</td><td>{{ $e->department }}</td><td>{{ $e->category }}</td><td>₹{{ number_format($e->amount,2) }}</td><td>{{ $e->status }}</td><td>@if($e->status==='pending')<form method="POST" action="{{ route('tagore.inventory.expense.decide',$e->id) }}" style="display:inline">@csrf @method('PATCH')<input type="hidden" name="status" value="approved"><button class="tg-btn">Approve</button></form><form method="POST" action="{{ route('tagore.inventory.expense.decide',$e->id) }}" style="display:inline">@csrf @method('PATCH')<input type="hidden" name="status" value="rejected"><button class="tg-btn danger">Reject</button></form>@endif</td></tr>@endforeach</tbody></table></div></section>
<section class="tg-card"><h2>Assets</h2><div class="tg-table-wrap"><table><thead><tr><th>Tag</th><th>Name</th><th>Category</th><th>Cost</th><th>Department</th><th>Status</th></tr></thead><tbody>@foreach($assets as $a)<tr><td>{{ $a->asset_tag }}</td><td>{{ $a->name }}</td><td>{{ $a->category }}</td><td>₹{{ number_format($a->cost,2) }}</td><td>{{ $a->department }}</td><td>{{ $a->status }}</td></tr>@endforeach</tbody></table></div></section>
</div></div>
@endsection
