<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Private Fee Vault · TagoreK12</title><link rel="stylesheet" href="{{ asset('tagore-erp.css') }}"></head>
<body><main class="tg-shell">
<header class="tg-topbar"><div class="tg-brand"><div class="tg-logo">T</div><div><strong>TagoreK12</strong><span>Private financial archive</span></div></div><div class="tg-user">Owner-only</div></header>
<nav class="tg-nav"><a href="{{ route('tagore.dashboard') }}">ERP Home</a><a href="{{ route('tagore.fees.accounts') }}">Accounts</a><a href="{{ route('tagore.fees.editor') }}">Fee Editor</a><a href="{{ route('tagore.fees.vault') }}">Private Vault</a></nav>
<section class="tg-hero"><h1>Private Fee Vault</h1><p>Original historical fee records, retained separately from the editable ERP ledger. Access is restricted to the configured vault owner and every lookup is logged.</p></section>
<section class="card" style="padding:22px"><form method="get" class="tg-form"><div class="tg-field" style="grid-column:1/-1"><label>Find a student</label><input name="q" value="{{ $q }}" placeholder="Student name, ID or email" autofocus></div><div><button type="submit">Search archive</button></div></form></section>
@if($q!=='')<section class="card" style="padding:22px;margin-top:18px"><div class="tg-section-head"><h2>Students</h2><span class="tg-kpi-label">{{ $students->count() }} result(s)</span></div>
@forelse($students as $s)<div style="padding:14px 0;border-bottom:1px solid #e6eaf0"><a href="{{ route('tagore.fees.vault.student',$s->id) }}" style="font-weight:800;color:#1f5eff;text-decoration:none">{{ $s->name }}</a><div class="tg-kpi-label">ID {{ $s->id }} · {{ $s->email ?: 'No email' }}</div></div>@empty<div class="tg-kpi-label">No student found.</div>@endforelse</section>@endif
</main></body></html>