@extends('layouts.app')
@section('content')
<link rel="stylesheet" href="{{ asset('tagore-erp.css') }}">
<div class="tg-app"><div class="tg-shell">
<header class="tg-topbar"><div class="tg-brand"><div class="tg-logo">T</div><div><strong>TagoreK12</strong><span>Platform Services</span></div></div><a class="tg-btn" href="{{ route('tagore.dashboard') }}">ERP Home</a></header>
@if(session('success'))<div class="tg-alert success">{{ session('success') }}</div>@endif
@if($errors->any())<div class="tg-alert danger">{{ $errors->first() }}</div>@endif
<section class="tg-hero"><div><span class="tg-eyebrow">Platform</span><h1>Alumni, Financing, CMS, Social & Automation</h1><p>Persistent configuration and workflows for the remaining Studybase-style platform capabilities.</p></div></section>
<section class="tg-card"><h2>Alumni profile</h2><form class="tg-form" method="POST" action="{{ route('tagore.platform.alumni') }}">@csrf<div class="tg-grid"><label class="tg-field"><span>Institution</span><select name="institution_id">@foreach($institutions as $i)<option value="{{ $i->id }}">{{ $i->display_name }}</option>@endforeach</select></label><label class="tg-field"><span>Student ID</span><input type="number" name="student_id" required></label><label class="tg-field"><span>Passout year</span><input type="number" name="passout_year"></label><label class="tg-field"><span>Course</span><input name="course"></label><label class="tg-field"><span>Current organisation</span><input name="current_org"></label><label class="tg-field"><span>Designation</span><input name="designation"></label><label class="tg-field"><span>Phone</span><input name="phone"></label><label class="tg-field"><span>Email</span><input name="email" type="email"></label></div><button class="tg-btn primary">Save alumni</button></form></section>
<section class="tg-card"><h2>Alumni event</h2><form class="tg-form" method="POST" action="{{ route('tagore.platform.event') }}">@csrf<div class="tg-grid"><label class="tg-field"><span>Institution</span><select name="institution_id">@foreach($institutions as $i)<option value="{{ $i->id }}">{{ $i->display_name }}</option>@endforeach</select></label><label class="tg-field"><span>Title</span><input name="title" required></label><label class="tg-field"><span>Starts</span><input type="datetime-local" name="starts_at" required></label><label class="tg-field"><span>Ends</span><input type="datetime-local" name="ends_at"></label><label class="tg-field" style="grid-column:1/-1"><span>Description</span><textarea name="description"></textarea></label></div><button class="tg-btn primary">Create event</button></form></section>
<section class="tg-card"><h2>Fee financing / EMI plan</h2><form class="tg-form" method="POST" action="{{ route('tagore.platform.finance') }}">@csrf<div class="tg-grid"><label class="tg-field"><span>Institution</span><select name="institution_id">@foreach($institutions as $i)<option value="{{ $i->id }}">{{ $i->display_name }}</option>@endforeach</select></label><label class="tg-field"><span>Name</span><input name="name" required></label><label class="tg-field"><span>Principal</span><input name="amount" type="number" step="0.01" required></label><label class="tg-field"><span>Tenure months</span><input name="tenure_months" type="number" min="1" required></label><label class="tg-field"><span>Interest % annual</span><input name="interest_rate" type="number" step="0.0001" value="0"></label><label class="tg-field"><span>Processing fee</span><input name="processing_fee" type="number" step="0.01" value="0"></label><label class="tg-field"><span>Provider</span><input name="provider"></label></div><button class="tg-btn primary">Create finance plan</button></form></section>
<section class="tg-card"><h2>Website CMS page</h2><form class="tg-form" method="POST" action="{{ route('tagore.platform.page') }}">@csrf<div class="tg-grid"><label class="tg-field"><span>Institution</span><select name="institution_id">@foreach($institutions as $i)<option value="{{ $i->id }}">{{ $i->display_name }}</option>@endforeach</select></label><label class="tg-field"><span>Slug</span><input name="slug" required></label><label class="tg-field"><span>Title</span><input name="title" required></label><label class="tg-field"><span>Status</span><select name="status"><option>draft</option><option>published</option></select></label><label class="tg-field" style="grid-column:1/-1"><span>Body</span><textarea name="body" rows="6"></textarea></label><label class="tg-field"><span>Meta title</span><input name="meta_title"></label><label class="tg-field"><span>Meta description</span><input name="meta_description"></label></div><button class="tg-btn primary">Save page</button></form></section>
<section class="tg-card"><h2>Internal social post</h2><form class="tg-form" method="POST" action="{{ route('tagore.platform.post') }}">@csrf<div class="tg-grid"><label class="tg-field"><span>Institution</span><select name="institution_id">@foreach($institutions as $i)<option value="{{ $i->id }}">{{ $i->display_name }}</option>@endforeach</select></label><label class="tg-field"><span>Group</span><input name="group_name"></label><label class="tg-field"><span>Title</span><input name="title"></label><label class="tg-field" style="grid-column:1/-1"><span>Post</span><textarea name="body" required></textarea></label></div><button class="tg-btn primary">Publish post</button></form></section>
<section class="tg-card"><h2>Automation rule</h2><form class="tg-form" method="POST" action="{{ route('tagore.platform.automation') }}">@csrf<div class="tg-grid"><label class="tg-field"><span>Institution</span><select name="institution_id">@foreach($institutions as $i)<option value="{{ $i->id }}">{{ $i->display_name }}</option>@endforeach</select></label><label class="tg-field"><span>Name</span><input name="name" required></label><label class="tg-field"><span>Trigger</span><input name="trigger" placeholder="fee.overdue"></label><label class="tg-field"><span>Action</span><input name="action" placeholder="send.notification"></label><label class="tg-field"><span>Schedule</span><input name="schedule" placeholder="daily"></label><label class="tg-field"><span>Config JSON</span><textarea name="config_json"></textarea></label></div><button class="tg-btn primary">Save automation</button></form></section>
<section class="tg-card"><h2>Integration</h2><form class="tg-form" method="POST" action="{{ route('tagore.platform.integration') }}">@csrf<div class="tg-grid"><label class="tg-field"><span>Institution</span><select name="institution_id">@foreach($institutions as $i)<option value="{{ $i->id }}">{{ $i->display_name }}</option>@endforeach</select></label><label class="tg-field"><span>Name</span><input name="name" required></label><label class="tg-field"><span>Provider</span><input name="provider" placeholder="GPS / WhatsApp / Facebook / Bank"></label><label class="tg-field"><span>Type</span><input name="type" placeholder="api"></label><label class="tg-field" style="grid-column:1/-1"><span>Configuration JSON</span><textarea name="config_json" placeholder='{"endpoint":"...","api_key":"..."}'></textarea></label></div><button class="tg-btn primary">Save integration</button></form></section>
<section class="tg-card"><h2>Branded creative template</h2><form class="tg-form" method="POST" action="{{ route('tagore.platform.creative') }}">@csrf<div class="tg-grid"><label class="tg-field"><span>Institution</span><select name="institution_id">@foreach($institutions as $i)<option value="{{ $i->id }}">{{ $i->display_name }}</option>@endforeach</select></label><label class="tg-field"><span>Name</span><input name="name" required></label><label class="tg-field"><span>Template type</span><input name="template_type" placeholder="certificate / ID / social"></label><label class="tg-field"><span>Template JSON</span><textarea name="template_json"></textarea></label><label class="tg-field"><span>Brand JSON</span><textarea name="brand_json" placeholder='{"logo":"...","primary":"#000000"}'></textarea></label></div><button class="tg-btn primary">Save template</button></form></section>
</div></div>
@endsection
