@php use Illuminate\Support\Str; @endphp
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>My Staff Center | TagoreK12</title>
<style>body{font-family:system-ui,-apple-system,sans-serif;margin:0;background:#f4f7fb;color:#172033}.shell{max-width:1200px;margin:auto;padding:24px 16px 60px}.card{background:#fff;border:1px solid #e2e8f0;border-radius:12px;padding:16px;margin-top:16px}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.metric b{display:block;font-size:28px}.muted{color:#64748b;font-size:13px}form{display:flex;gap:8px;flex-wrap:wrap}input,select,textarea,button{padding:9px;border:1px solid #cbd5e1;border-radius:8px;background:#fff;font:inherit}textarea{min-height:80px;width:100%}table{width:100%;border-collapse:collapse;margin-top:10px}th,td{padding:9px;border-bottom:1px solid #edf2f7;text-align:left;font-size:13px}a{color:#2563eb;text-decoration:none}.tag{display:inline-block;padding:3px 7px;border-radius:999px;background:#eef2ff;font-size:12px}@media(max-width:800px){.grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:500px){.grid{grid-template-columns:1fr}}</style></head>
<body><div class="shell"><p><a href="{{ route('tagore.dashboard') }}">← Dashboard</a></p>
<div class="card"><h1 style="margin:0 0 6px">My Staff Center</h1><div class="muted">{{ $user->name }} · {{ $user->email }} · {{ $institution->display_name }}</div></div>
<div class="grid"><div class="card metric"><span class="muted">Attendance</span><b>{{ $attendancePercent !== null ? $attendancePercent.'%' : '—' }}</b></div><div class="card metric"><span class="muted">Assigned tasks</span><b>{{ $tasks->count() }}</b></div><div class="card metric"><span class="muted">Leave requests</span><b>{{ $leaves->count() }}</b></div><div class="card metric"><span class="muted">Reviews</span><b>{{ $reviews->count() }}</b></div></div>
<div class="card"><h2>Apply for leave</h2><form method="post" action="{{ route('tagore.staff.self.leave') }}">@csrf
<select name="leave_type_id" required><option value="">Leave type</option>@foreach($leaveTypes as $type)<option value="{{ $type->id }}">{{ $type->name }}{{ $type->max_no_of_days ? ' · max '.$type->max_no_of_days : '' }}</option>@endforeach</select>
<input type="date" name="from_date" required><input type="date" name="to_date" required><select name="session" required><option value="day">Full day</option><option value="forenoon">Forenoon</option><option value="afternoon">Afternoon</option></select><textarea name="remarks" placeholder="Reason / remarks"></textarea><button type="submit">Submit leave application</button></form></div>
<div class="card"><h2>My leave history</h2><table><tr><th>Dates</th><th>Type</th><th>Session</th><th>Status</th><th>Approver</th><th>Remarks</th><th>Action</th></tr>@forelse($leaves as $leave)<tr><td>{{ date('d M Y',strtotime($leave->from_date)) }} – {{ date('d M Y',strtotime($leave->to_date)) }}</td><td>{{ $leave->leave_type ?: '—' }}</td><td>{{ ucfirst($leave->session ?: 'day') }}</td><td><span class="tag">{{ ucfirst($leave->status) }}</span></td><td>{{ $leave->approver_name ?: '—' }}</td><td>{{ Str::limit($leave->remarks ?: $leave->comments,80) }}</td><td>@if($leave->status==='pending')<form method="post" action="{{ route('tagore.staff.self.leave.cancel',$leave->id) }}">@csrf @method('PATCH')<button>Cancel</button></form>@else—@endif</td></tr>@empty<tr><td colspan="7">No leave applications yet.</td></tr>@endforelse</table></div>
<div class="card"><h2>My work</h2><table><tr><th>Task</th><th>Department</th><th>Status</th><th>Progress</th><th>Priority</th><th>Due</th></tr>@forelse($tasks as $task)<tr><td>{{ $task->title }}</td><td>{{ $task->department ?: '—' }}</td><td>{{ ucfirst(str_replace('_',' ',$task->status)) }}</td><td>{{ $task->progress }}%</td><td>{{ ucfirst($task->priority) }}</td><td>{{ $task->due_at ? date('d M Y H:i',strtotime($task->due_at)) : '—' }}</td></tr>@empty<tr><td colspan="6">No assigned tasks.</td></tr>@endforelse</table></div>
<div class="card"><h2>Manager reviews</h2><table><tr><th>Date</th><th>Task</th><th>Type</th><th>Outcome</th><th>Manager</th><th>Follow-up</th><th>Notes</th></tr>@forelse($reviews as $review)<tr><td>{{ date('d M Y',strtotime($review->created_at)) }}</td><td>{{ $review->task_title ?: '—' }}</td><td>{{ ucfirst(str_replace('_',' ',$review->review_type)) }}</td><td>{{ ucfirst(str_replace('_',' ',$review->outcome)) }}</td><td>{{ $review->manager_name }}</td><td>{{ $review->follow_up_at ? ($review->completed_at ? 'Closed' : date('d M Y H:i',strtotime($review->follow_up_at))) : '—' }}</td><td>{{ Str::limit($review->notes,140) }}</td></tr>@empty<tr><td colspan="7">No reviews recorded.</td></tr>@endforelse</table></div>
</div></body></html>